"use client";

import { useEffect } from "react";
import { writeToClipboard } from "@/lib/clipboard";
import { showToast } from "@/lib/toast";

// Single-letter → readable-name substitutions. Ported verbatim from js/content/formatting.js VAR_MAP.
const VAR_MAP: Record<string, string> = {
  T: "time",
  t: "time",
  λ: "arrival rate",
  μ: "service rate",
  τ: "latency",
  ρ: "utilization",
  ω: "frequency",
  n: "size",
  N: "total",
  m: "count",
  k: "partitions",
  B: "block size",
  b: "bits",
  W: "width",
  H: "height",
  p: "probability",
  q: "failure prob",
  σ: "std dev",
  α: "alpha",
  β: "beta",
  θ: "threshold",
  f: "function",
  g: "growth",
  L: "length",
  S: "space",
};

function substituteLatex(latex: string): string {
  return latex.replace(
    /\\[a-zA-Z]+|(?<!\\)(?<![a-zA-Zα-ωΑ-Ω])([a-zA-Zα-ωΑ-Ω])(?=[^a-zA-Zα-ωΑ-Ω_{]|$)/gu,
    (match) =>
      match.startsWith("\\") ? match : VAR_MAP[match] ? `\\text{${VAR_MAP[match]}}` : match,
  );
}

function toolbarFor(block: HTMLElement): HTMLElement {
  let toolbar = block.querySelector<HTMLElement>(".katex-toolbar");
  if (!toolbar) {
    toolbar = document.createElement("div");
    toolbar.className = "katex-toolbar";
    block.style.position = "relative";
    block.appendChild(toolbar);
  }
  return toolbar;
}

// Adds an αβ variable-name toggle + copy-LaTeX button to each .katex-display block.
// Ported from js/content/formatting.js addFormulaToggle / addLatexCopyButtons.
export function LatexToggle() {
  useEffect(() => {
    const root = document.querySelector<HTMLElement>(".markdown-body");
    if (!root) return;
    const blocks = [...root.querySelectorAll<HTMLElement>(".katex-display")];
    if (!blocks.length) return;

    const cleanups: Array<() => void> = [];
    let katexMod: typeof import("katex").default | null = null;

    for (const block of blocks) {
      const annotation = block.querySelector("annotation[encoding='application/x-tex']");
      if (!annotation) continue;
      const original = (annotation.textContent ?? "").trim();
      const substituted = substituteLatex(original);
      const toolbar = toolbarFor(block);

      const copyBtn = document.createElement("button");
      copyBtn.type = "button";
      copyBtn.className = "copy-btn latex-copy-btn";
      copyBtn.title = "Copy LaTeX";
      copyBtn.setAttribute("aria-label", "Copy LaTeX");
      copyBtn.textContent = "⧉";
      const onCopy = (e: MouseEvent) => {
        e.stopPropagation();
        writeToClipboard(original)
          .then(() => {
            copyBtn.textContent = "✓";
            copyBtn.classList.add("copied");
            setTimeout(() => {
              copyBtn.textContent = "⧉";
              copyBtn.classList.remove("copied");
            }, 2000);
          })
          .catch(() => showToast("Couldn't copy to clipboard", { variant: "error" }));
      };
      copyBtn.addEventListener("click", onCopy);
      toolbar.appendChild(copyBtn);
      cleanups.push(() => {
        copyBtn.removeEventListener("click", onCopy);
        copyBtn.remove();
      });

      if (substituted === original) continue;

      const katexSpan = block.querySelector<HTMLElement>(".katex");
      if (!katexSpan?.parentNode) continue;
      const wrapper = document.createElement("span");
      wrapper.className = "formula-toggle-wrapper";
      katexSpan.parentNode.insertBefore(wrapper, katexSpan);
      wrapper.appendChild(katexSpan);

      let expanded = false;
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "formula-toggle-btn";
      btn.title = "Toggle variable names";
      btn.setAttribute("aria-label", "Toggle variable names");
      btn.textContent = "αβ";
      const runToggle = async () => {
        const katex = katexMod ?? (katexMod = (await import("katex")).default);
        expanded = !expanded;
        btn.classList.toggle("active", expanded);
        btn.title = expanded ? "Show symbols" : "Toggle variable names";
        try {
          const tmp = document.createElement("span");
          // katex.renderToString output is generated by KaTeX from build-authored LaTeX
          tmp.innerHTML = katex.renderToString(expanded ? substituted : original, {
            displayMode: false,
            throwOnError: false,
          });
          wrapper.replaceChildren(tmp.firstElementChild ?? tmp);
        } catch {
          expanded = !expanded;
          btn.classList.toggle("active", expanded);
        }
      };
      const onToggle = (e: MouseEvent) => {
        e.stopPropagation();
        void runToggle();
      };
      btn.addEventListener("click", onToggle);
      toolbar.appendChild(btn);
      cleanups.push(() => {
        btn.removeEventListener("click", onToggle);
        btn.remove();
      });
    }

    return () => {
      for (const c of cleanups) c();
    };
  }, []);

  return null;
}
