import { copyFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { buildContent } from "../lib/content/index.ts";

// Generated by the content build:
const GENERATED_FILES = [
  "search-index.json",
  "backlinks.json",
  "broken-links.json",
  "bridges.json",
  "previews.json",
  "complexity-tables.json",
];

// Hand-authored, tracked in data/, copied into the git-ignored public/data/ for the app + SW:
const AUTHORED_FILES = ["glossary.json", "synonyms.json", "shortcuts.json", "summaries.json"];

await buildContent();

const to = "public/data";
mkdirSync(to, { recursive: true });
for (const f of GENERATED_FILES) copyFileSync(join("lib/content/generated", f), join(to, f));
for (const f of AUTHORED_FILES) copyFileSync(join("data", f), join(to, f));
